name: rServerInfo
main: net.rdevs.plugins.rserverinfo.RServerInfo
version: 1.1
commands:
  teamspeak:
    description: You can see the teamspeak ip!
    aliases: [ts, ts3, ts2]
  website:
    description: You can see the website address!
    aliases: [web, site]
  discord:
    description: You can see the discord invite code!
  twitter:
    description: You can see the servers twitter!
  forums:
    description: You can see the servers forums!
    aliases: [forum, fourms]
  rserverinfo:
    description: You can view plugin information and  reload the config file for this plugin.